# Generated by Django 4.1.2 on 2022-10-12 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=180)),
                ('last_name', models.CharField(blank=True, max_length=180)),
                ('email', models.CharField(max_length=180)),
                ('password', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 10, 21, 2, 634235, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
